### GET Contact List
GET http://127.0.0.1:8000/api/v1/contact/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET Contact List filtered for type private
GET http://127.0.0.1:8000/api/v1/contact/?type=private
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CREATE Contact
POST http://127.0.0.1:8000/api/v1/contact/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
  "name": "NewTesterin",
  "type": "company",
  "email": "user@example.com",
  "salutation": "Welcome Honey"
}

### GET Specific Contact
GET http://127.0.0.1:8000/api/v1/contact/3/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CHANGE Specific Contact
PUT http://127.0.0.1:8000/api/v1/contact/4/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
  "name": "Testerin",
  "type": "private",
  "email": "test@test.com",
  "salutation": "Welcome Madam"
}

### DELETE Specific Contact
DELETE http://127.0.0.1:8000/api/v1/contact/4/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

### GET Address List
GET http://127.0.0.1:8000/api/v1/address/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CREATE Address
POST http://127.0.0.1:8000/api/v1/address/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
    "street": "Fantasyroad",
    "zip": "777",
    "city": "Imaging",
    "country": "1",
    "contact": 2
}

### GET Specific Address
GET http://127.0.0.1:8000/api/v1/address/5/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CHANGE Specific Contact
PUT http://127.0.0.1:8000/api/v1/address/5/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
    "street": "Testroad",
    "zip": "999",
    "city": "Testcity",
    "country": "1",
    "contact": 1
}

### DELETE Specific Contact
DELETE http://127.0.0.1:8000/api/v1/address/5/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

### GET Invoice List
GET http://127.0.0.1:8000/api/v1/invoice/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET Invoice List inclusive search for contact_name "Tester"
GET http://127.0.0.1:8000/api/v1/invoice/?search=Tester
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CREATE Invoice
POST http://127.0.0.1:8000/api/v1/invoice/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
    "title": "MoneyCash",
    "body": "We want our money",
    "date": "2021-05-20",
    "due": "2021-05-30",
    "condition": "string",
    "address": 1
}

### GET Specific Invoice
GET http://127.0.0.1:8000/api/v1/invoice/3/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### UPDATE Specific Invoice
PUT http://127.0.0.1:8000/api/v1/invoice/3/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{
    "title": "Bill",
    "body": "Bill for Tester",
    "date": "2021-06-20",
    "due": "2021-06-25",
    "condition": "string",
    "address": 1
}

### DELETE Specific Invoice
DELETE http://127.0.0.1:8000/api/v1/invoice/4/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET InvoicePosition List
GET http://127.0.0.1:8000/api/v1/invoiceposition/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### CREATE InvoicePosition
POST http://127.0.0.1:8000/api/v1/invoiceposition/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{

    "title": "Drugs",
    "body": "shiny",
    "amount": "999",
    "quantity": 3,
    "invoice": 3

}

### GET Specific InvoicePosition
GET http://127.0.0.1:8000/api/v1/invoiceposition/3/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### UPDATE Specific InvoicePosition
PUT http://127.0.0.1:8000/api/v1/invoiceposition/3/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39
Content-Type: application/json

{

    "title": "Games",
    "body": "Testing Games",
    "amount": "5",
    "quantity": 10,
    "invoice": 3

}

### DELETE Specific InvoicePosition
DELETE http://127.0.0.1:8000/api/v1/invoiceposition/5/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET Countries List
GET http://127.0.0.1:8000/api/v1/country/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET Countries List inclusive search for value "Schweiz"
GET http://127.0.0.1:8000/api/v1/country/?search=Schweiz
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39

### GET Specific Country
GET http://127.0.0.1:8000/api/v1/country/2/
Authorization: Token bd82975ec513c09b2da0434b9f9bfea2204baf39